### PR TITLE
Update pool definitions and python script to fetch groups from adapools and adastat

### PR DESCRIPTION
**Pull request by rdlrt**
Create updated pool clusters and output mismatch from either side to descrepancy.json

### CODE REVIEW

**Review by ashisherc — APPROVED** [review]

**Review by PegasusPool — APPROVED** [review]
LGTM

**Review by Scitz0 — APPROVED** [review]
👍

**Review by hodlonaut — APPROVED** [review]
Looks good

**Comment by PegasusPool** [comment]
The rename from `pool_cluster.json` to `pool_clusters.json` caught me off guard :sweat_smile:

**Pull request merged**
